# Generated by Django 6.0.1 on 2026-05-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_deletelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
