# Generated by Django 6.0.1 on 2026-08-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_titlereservation_course_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='editlog',
            name='changes',
            field=models.JSONField(blank=True, default=list, help_text='List of {field, old, new} dicts describing what changed.'),
        ),
    ]
