# Generated by Django 6.0.1 on 2026-08-25 12:31

from django.db import migrations, models


def convert_admin_to_content_manager(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='ADMIN').update(role='CONTENT_MANAGER')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_editlog_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('CONTENT_MANAGER', 'Content Manager'), ('TEACHER', 'Teacher'), ('USER', 'User')], default='USER', max_length=20),
        ),
        migrations.RunPython(convert_admin_to_content_manager, migrations.RunPython.noop),
    ]
