# Generated by Django 6.0.1 on 2026-10-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlereservation',
            name='keywords',
            field=models.CharField(default='', max_length=500),
        ),
    ]
