# Generated by Django 6.0.1 on 2026-02-27 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=500)),
                ('year', models.IntegerField(help_text='Enter a year between 2019 and the current year.', validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2026)])),
                ('abstract', models.TextField()),
                ('panelists', models.CharField(max_length=500)),
                ('file', models.FileField(help_text='Upload the full research file (PDF or Word format).', upload_to='research_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])])),
                ('course', models.CharField(choices=[('BSCS', 'BSCS'), ('BSIT', 'BSIT'), ('BSEMC', 'BSEMC')], max_length=5)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
