# Generated by Django 6.0.1 on 2026-09-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_update_video_demo_link_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='Name of the embedding model used (e.g. gemini-embedding-001).', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the search embedding was last generated.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_version',
            field=models.IntegerField(default=0, help_text='Version of the embedding model used (bump to force re-embedding).'),
        ),
        migrations.AddField(
            model_name='document',
            name='search_embedding',
            field=models.JSONField(blank=True, help_text='Embedding vector (list of floats) used for semantic cosine search.', null=True),
        ),
    ]
